import {Food} from './app/shared/models/Food';
import { Tag } from './app/shared/models/Tag';

export const sample_foods: Food[] = [
  {
    id:'1',
    name: 'Samosa',
    cookTime: '5-10',
    price: 30,
    favorite: false,
    origins: ['indian'],
    stars: 4.5,
    imageUrl: 'assets/food-1.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'2',
    name: 'Chhole & Rice',
    price: 80,
    cookTime: '20-30',
    favorite: true,
    origins: ['indian'],
    stars: 4.7,
    imageUrl: 'assets/food-2.jpg',
    tags: ['Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 50,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    stars: 3.5,
    imageUrl: 'assets/food-3.jpg',
    tags: ['FastFood', 'Burger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 2,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    stars: 3.3,
    imageUrl: 'assets/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Biryani',
    price: 160,
    cookTime: '30-40',
    favorite: false,
    origins: ['indian', 'asia'],
    stars: 5.0,
    imageUrl: 'assets/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 180,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    stars: 3.0,
    imageUrl: 'assets/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Spicy Cheese Burger',
    price: 60,
    cookTime: '20-30',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-7.jpg',
    tags: ['FastFood', 'Burger'],
  },
  {
    id:'8',
    name: 'Vegetables Magento Pizza',
    price: 200,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    stars: 4.0,
    imageUrl: 'assets/food-8.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]

export const sample_tags:Tag[] = [
  { name: 'All', count: 8 },
  { name: 'FastFood', count: 6 },
  { name: 'Pizza', count: 2 },
  { name: 'Lunch', count: 3 },
  // { name: 'SlowFood', count: 2 },
  { name: 'Burger', count: 2 },
  { name: 'Fry', count: 2 },
  // { name: 'Soup', count: 1 },
]
